=== Goncalves745/inf22tig11/ficheiros/servicos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="servicos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="servico" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tipo_servico" type="xs:string"/>
              <xs:element name="descricao_servico" type="xs:string"/>
              <xs:element name="descricao_servico2" type="xs:string"/>
              <xs:element name="descricao_servico3" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Goncalves745/inf22tig11/ficheiros/servicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<servicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="servicos.xsd">
  <servico>
    <tipo_servico>Corte de Pelo</tipo_servico>
    <descricao_servico>Corte conforme a preferência do cliente.</descricao_servico>
    <descricao_servico2>Remoção de pelo em excesso.</descricao_servico2>
    <descricao_servico3>Desembaraço e escovação.</descricao_servico3>
  </servico>
  <servico>
    <tipo_servico>Lavagem e Hidratação</tipo_servico>
    <descricao_servico>Banhos suaves e relaxantes.</descricao_servico>
    <descricao_servico2>Produtos de alta qualidade para peles sensíveis.</descricao_servico2>
    <descricao_servico3>Hidratação profunda para pelos macios e brilhantes.</descricao_servico3>
  </servico>
  <servico>
    <tipo_servico>Cuidados Especiais</tipo_servico>
    <descricao_servico>Manutenção das unhas</descricao_servico>
    <descricao_servico2>Tratamentos para pele seca ou sensível.</descricao_servico2>
    <descricao_servico3>Remoção de nós.</descricao_servico3>
  </servico>
</servicos>
